version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: docker/rails/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - '33306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  redis:
    image: redis:5.0.5
    ports:
      - 6399:6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  bundle:
  mysql_data:
  redis_data:
